id: I597A9803
legacy_id: P009395
ocr_import_info:
  bdrc_scan_id: W22128
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T11:07:16'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T20:44:32.377694+00:00'
last_modified: 2022-09-02 04:45:10.142680
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22128
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW22128
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཤུགས་ལྡན་བེའུ་བུམ། ༼ལྷ་ས་པར་མ།༽
  author: ཁྲི་བྱང ༠༣་བློ་བཟང་ཡེ་ཤེས་བསྟན་འཛིན་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.5844451700470952
  ocr_word_median_confidence_index: 0.6000000238418579
quality: null
bases:
  I1KG11944:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG11944
      total_pages: 778
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG11944.txt
    statistics:
      ocr_word_median_confidence_index: 0.6100000143051147
      ocr_word_mean_confidence_index: 0.5924434235567057
    legacy_id: v001
  I1KG11945:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG11945
      total_pages: 708
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG11945.txt
    statistics:
      ocr_word_median_confidence_index: 0.5799999833106995
      ocr_word_mean_confidence_index: 0.5740564301768223
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
