id: P009395
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 19:36:44.689510
source_metadata:
  id: bdr:W22128
  title: ཤུགས་ལྡན་བེའུ་བུམ། ༼ལྷ་ས་པར་མ།༽
  author: ''
  volumes:
    37368bf42206483ea93e177a00ab9609:
      image_group_id: I1KG11944
      title: ''
      volume_number: 1
      total_pages: 778
      base_file: v001.txt
    5549f82c116e4cdbb5edb24d0febd00a:
      image_group_id: I1KG11945
      title: ''
      volume_number: 2
      total_pages: 708
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
